### ISSUE TITLE
需要在config.ini文件中配置支付密码

### ISSUE THREAD

**Issue by zimo0825** [cycz/jdBuyMask#1]
这个怎么配置没看见这个文件，这个注释在410行

**Comment by cycz** [comment]
你有出现这个下单失败的情况吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"紫陌"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月5日(星期三) 下午4:41
收件人:&nbsp;"cycz/jdBuyMask"<jdBuyMask@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[cycz/jdBuyMask] 需要在config.ini文件中配置支付密码 (#1)




这个怎么配置没看见这个文件，这个注释在410行

**Comment by zimo0825** [comment]
口罩还没抢到的所有没遇到，但是在使用优惠券、白条、京豆、京东支付、京东E卡、账户余额等业务时需要验证支付密码，如何使用这些应该就无法提交订单了吧

**Comment by cycz** [comment]
已经提交了，再拉一下。
我之前用运费卷还可以，其他优惠卷没有尝试&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "紫陌"<notifications@github.com&gt;; 
发送时间: 2020年2月5日(星期三) 下午4:49
收件人: "cycz/jdBuyMask"<jdBuyMask@noreply.github.com&gt;; 
抄送: "cyz"<838143144@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [cycz/jdBuyMask] 需要在config.ini文件中配置支付密码 (#1)




口罩还没抢到的所有没遇到，但是在使用优惠券、白条、京豆、京东支付、京东E卡、账户余额等业务时需要验证支付密码，如何使用这些应该就无法提交订单了吧

**Comment by zimo0825** [comment]
OK

**Comment by silenceben** [comment]
我试了下，主要有红包之类的阻碍，需要输入密码。这个时候下一个在线支付的订单，随便买点什么，把红包用掉，但是可以不支付，就不会出现这个情况。

**Comment by cycz** [comment]
> 我试了下，主要有红包之类的阻碍，需要输入密码。这个时候下一个在线支付的订单，随便买点什么，把红包用掉，但是可以不支付，就不会出现这个情况。

等我有红包的时候调试一下。23333
