### ISSUE TITLE
新版本运行出错

### ISSUE THREAD

**Issue by messiisgod** [cycz/jdBuyMask#14]
Traceback (most recent call last):
  File "D:/py工程/jdmask/jdBuyMask.py", line 129, in <module>
    name, value = item.strip().split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by cycz** [comment]
你cookie没改好吧。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"messiisgod"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月6日(星期四) 下午3:29
收件人:&nbsp;"cycz/jdBuyMask"<jdBuyMask@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[cycz/jdBuyMask] 新版本运行出错 (#14)




Traceback (most recent call last):
 File "D:/py工程/jdmask/jdBuyMask.py", line 129, in 
 name, value = item.strip().split('=', 1)
 ValueError: not enough values to unpack (expected 2, got 1)
