### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by picfan** [cycz/jdBuyMask#16]
Traceback (most recent call last):
  File "D:/jd/new.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

老师您好我是新手
直接运行脚本提示这个我把
beautifulsoup4==4.8.2
requests==2.22.0

添加进去提示
invalid syntax
为了买口罩真的太感谢这个脚本了可是我弄不成
希望老师能教教我

**Comment by haiyangzhijia** [comment]
pip install beautifulsoup4

**Comment by cycz** [comment]
你先百度一下python 和 pip
