### ISSUE TITLE
京东的cookie有没有时效？

### ISSUE THREAD

**Issue by 935714648** [cycz/jdBuyMask#2]

**Comment by cycz** [comment]
当然，不过会试不试去请求一次，应该能延长可用的时长。目前我自己测一天都可用

**Comment by 935714648** [comment]
有些商品特定地区不出售的也会下单，之后报错直接退出。

**Comment by cycz** [comment]
> 有些商品特定地区不出售的也会下单，之后报错直接退出。

可以把商品id发给我吗，我调试一下。

**Comment by 935714648** [comment]
抱歉现在才看见，商品ID：100010159778

**Comment by tychxn** [comment]
@cycz README 中备注一下参考的 repo 可好？
