### ISSUE TITLE
AreaTool.py文件提取skuids好像只能一条一条提取

### ISSUE THREAD

**Issue by 935714648** [cycz/jdBuyMask#23]
还是我的使用错误

**Comment by vonking** [comment]
就是个地区ID，你购买的东西就是同一个地址，一条就够了

**Comment by 935714648** [comment]
> 就是个地区ID，你购买的东西就是同一个地址，一条就够了

skuids是商品id,一条怎么够
area地区的id,这个id是统一的

**Comment by vonking** [comment]
> 就是个地区ID，你购买的东西就是同一个地址，一条就够了
> 
> skuids是商品id,一条怎么够
> area地区的id,这个id是统一的

哈哈，看错了。商品ID的话直接在京东商品页面复制就可以

**Comment by vonking** [comment]
用area tool输入多条是会出错

**Comment by 935714648** [comment]
> 用area tool输入多条是会出错
做个循环就行了，从url列表中逐条提取

**Comment by vonking** [comment]
Traceback (most recent call last):
File "C:\Users*\Desktop\Python\jdBuyMask-master_V2\jdBuyMask-master\jdBuyMask_V2.py", line 14, in 
from config.config import global_config
File "C:\Users*\Desktop\Python\jdBuyMask-master_V2\jdBuyMask-master\config\config.py", line 23, in 
global_config = Config()
File "C:\Users*****\Desktop\Python\jdBuyMask-master_V2\jdBuyMask-master\config\config.py", line 10, in init
raise FileNotFoundError("No such file: config.ini")
FileNotFoundError: No such file: config.ini
————————
老哥能看看哪里有问题吗

**Comment by cycz** [comment]
本意是告诉你们哪个是商品id，那个是地区id，地区id是统一的。

**Comment by cycz** [comment]
> config.ini

你这个文件的位置有改动吗

**Comment by vonking** [comment]
> config.ini
> 
> 你这个文件的位置有改动吗

位置没有改动，压缩包解压就在一个文件夹里面。

**Comment by cycz** [comment]
> > config.ini
> > 你这个文件的位置有改动吗
> 
> 位置没有改动，压缩包解压就在一个文件夹里面。

实在运行不起来 你就加我qq吧
