### ISSUE TITLE
下单地址与实际不符是什么造成的

### ISSUE THREAD

**Issue by lxdzh** [cycz/jdBuyMask#24]

**Comment by lxdzh** [comment]
刚刚使用v2版依旧不是默认地址。不知道为何，可否有大佬解答，难道是cookies的问题吗？

**Comment by cycz** [comment]
你自己去jd 电脑的页面下一单，看看是啥地址

**Comment by lxdzh** [comment]
默认地址。

**Comment by lxdzh** [comment]
@cycz 京东下单是默认地址，python是地址列表里面的一个地址

**Comment by cycz** [comment]
> @cycz 京东下单是默认地址，python是地址列表里面的一个地址

加我qq。838143144
