### ISSUE TITLE
skuid最大能存储100个ID  多了就会提示无货

### ISSUE THREAD

**Issue by zimo0825** [cycz/jdBuyMask#29]
raceback (most recent call last):
  File "E:/学习/python/口罩/2020.02.06/jdBuyMask-master/jdBuyMask_V2.py", line 484, in <module>
    inStockSkuid = check_stock()
  File "E:/学习/python/口罩/2020.02.06/jdBuyMask-master/jdBuyMask_V2.py", line 462, in check_stock
    if respjson[i]['StockStateName'] != '无货':
KeyError: '100006784140'

**Comment by pia** [comment]
我不到100个也这种提示，应该都这样

**Comment by zimo0825** [comment]
我只是大概数了下



---原始邮件---
发件人: "Changjun Sun"<notifications@github.com&gt;
发送时间: 2020年2月7日(星期五) 下午3:07
收件人: "cycz/jdBuyMask"<jdBuyMask@noreply.github.com&gt;;
抄送: "紫陌"<673087044@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [cycz/jdBuyMask] skuid最大能存储100个ID  多了就会提示无货 (#29)



我不到100个也这种提示，应该都这样

**Comment by pia** [comment]
skuids最后一个数字后面不用加逗号

求分享skuid列表

**Comment by zimo0825** [comment]
> skuids最后一个数字后面不用加逗号
> 
> 求分享skuid列表

skuids =100006784140,11609510701,11609507800,65402985519,65399049577,34197525576,1238056920,41157965868,41157965869,41157965870,41157965871,20111976846,65425149164,10653857950,10653857951,1938795,100005666820,1835968,1835967,1938788,1891756,100010439846,100009450890,100005818743,100011184496,100002690344,860176,3977082,100009130434,5707386,100011113858,6238439,100003712460,1938811,1938800,1060200558,1138381,3500471,851157,4979082,5572426,6046611,6046613,3623375,4052340,8872215,7814095,100004237845,8660516,5198045,5105967,100007285152,1564454,100006176160,100006877166,5481126,5326577,10728987754,100004142807,100006176206,2291608,100002824548,100001661013,100003680693,100002841169,10728987753,2291586,100010215646,100006176202,59381629579,100006176204,7043722,100001894238,7257333,100001894236,100001431455,7296030,7509643,7509641,7263128,60323904322,7498169,100010454866,100010572918,10977493054,10222629474,7509607,25411367334,25411367335,100011290370,100011293950,100011293928,100006248247,100006248247,5724402,4530633,4530595,5290414,3852111,100009441994,100009442472,100006066047,59959871345,59959871346,59959871348,59959871347,1138376,100005151507,100011294222,7498167,3083878,5322060,7914790

**Comment by VincentSit** [comment]
65466451629,65437208345,7498169,7498165,7263128,7498167,17449572304,37934196731,100001086804,56657322838,56657322841,100005294853,1938795,15595191653,15595191654,45923412989,100005088337,65451413573,100006784140,11609510701,11609507800,65402985519,65399049577,34197525576,1238056920,41157965868,41157965869,41157965870,41157965871,20111976846,65425149164,10653857950,10653857951,1938795,100005666820,1835968,1835967,1938788,1891756,100010439846,100009450890,100005818743,100011184496,100002690344,860176,3977082,100009130434,5707386,100011113858,6238439,100003712460,1938811,1938800,1060200558,1138381,3500471,851157,4979082,5572426,6046611,6046613,3828117,3621679,3623375,4052340,8872215,7814095,100004237845,8660516,5198045,5105967,100007285152,1564454,100006176160,100006877166,5481126,5326577,10728987754,100004142807,100006176206,2291608,100002824548,100001661013,100003680693,100002841169,10728987753,2291586,100010215646,100006176202,59381629579,100006176204,7043722,100001894238,7257333,100001894236,100001431455,7296030,7509643,7509641,7263128,60323904322,7498169,100010454866,100010572918,10977493054,10222629474,7509607,25411367334,25411367335,100011290370,100011293950,100011293928,100006248247,100006248177,5724402,4530633,4530595,5290414,3852111,100009441994,100009442472,100006066047,59959871345,59959871346,59959871348,59959871347,1138376,100005151507,100011294222,7498167,3083878,5322060,7914790,65444576693,65466250547,65466451629,100009450890,12144281496,45690470720,62359370823,62359370822,62359370820,62359370819,7498169,100006249999,65437208345,64422928809,1336984,45472790359,45476508432,62456885170,62456663069,100002957324,7764520,100002072425,100001998331,100002641826,100002068063,100002882922,100002810096,100002956964,100002340330,7764518,100011184496,59959871346,59959871345,59959871348,59959871347,100009134738,100009130434,1938795,100010454866,7043722,7257333,100009442472,100006066047,37950120499,38455799096,65427832836,11609510701,11609507800,100006445800,100002690344,100010439846,45095729071,851157,4993437,7498167,7263128,1835967,1835968,100005818743,100007184778,100006784128,100005151507,100009441994,100004024797,100004447743,5707386,10728987754,41157965870,65425149164,10653857950,10653857951,41157965871,41157965869,65402985519,1238056920,100006248247,65399049577,100006877166,41157965868,100011113858,6238439,100011294222,62408717970,100011293928,45479727464,13640548642,100011299904,100003712460,20111976846,1060200558,34197525576,5431086,5572426,3500471,4979082,6046611,6046613,7814095,5105967,5326577,100004142807,100002824548,100001661013,10977493054,100002841169,10222629474,2582352,3621679,4052340,100003680693,25411367334,10728987753,5481126,100011290370,45471064495,2291586,3623375,25411367335,3828117,100006248177,5290414,3852111,4530595,4530633,5724402,1138381,1938800,1938811,3977082,860176,1138376,100009109410,100009442176,65429694202,100006784140,1612617211,1612617212,7509607,60323904322,1938788,7296030,7509643,7509641,100003427129,1891756,100005666820,100010572918,100011293950,1337002,100011298204,1123893,100011298190,100008918926,1306166,100006252259,7814131,45471872750,45103563868,45480826976,62455823169,1306182,45475457977,100000284421,100002690356,100005088337,100006248245,100007662296,100010159728,100011040544,100011142220,11260989434,11300307432,11300343539,11748734210,1207831879,12380750178,12733802589,12783085564,12836354303,1317318,14927211877,16831249053,17449572304,19149113141,19225202919,20266165769,4061438,45789809933,45801275120,45923412989,46062340699,4618525,4642656,47902641330,49007836705,51137726168,5296279,5322060,56657322838,57203194276,57601623962,58693904867,6023863,62359370818,62359370821,65421371269,65425816569,65426813242,65456605713,7330603,8872215,100004237845,8660516,5198045,100007285152,1564454,100006176160,100006176206,2291608,100010215646,100006176202,59381629579,100006176204,100001894238,100001894236,100001431455,3083878,5174155,5174173,100007662312,10803442582,10803442583,1612613281,100001853901,3364866,100001410262,3335316,3606166,3842341,7914790,64994084930,64994084928,13486172528,13486172530,13486172527,64994084929,65454040199,100002690350,100002690384,100004092111,100004092117,100004092121,100004092125,100004092143,100006857202,100006989522,100006992518,100006992520,100009445348,100009445538,100010258482,100010638508,100010908190,10652011044,15941729623,1612617210,22753397779,35371843916,35502042992,35502042995,35668608578,35669407159,45185106048,45712329352,45801275121,48385661121,48385661122,48392511532,51137726179,54080043790,54080043791,54080043792,55521546969,58931474386,61202994740,62408717969,65420816726,65420816727,65425102594,65425102595,65425102596,65425149165,65444576693,7950392
