### ISSUE TITLE
ModuleNotFoundError: No module named 'log.jdlogger'; 'log' is not a package

### ISSUE THREAD

**Issue by linkagee** [cycz/jdBuyMask#33]
脚本无法运行，提示为：
ModuleNotFoundError: No module named 'log.jdlogger'; 'log' is not a package

**Comment by zylx0532** [comment]
pip install logger

**Comment by willyu320** [comment]
pip install logger 放在代码一开始是吗

**Comment by linkagee** [comment]
> pip install logger

Thanks! Tried "pip install log, jdlogger"都不是，原来是logger🤣
