### ISSUE TITLE
v2运行出错

### ISSUE THREAD

**Issue by xinxijishuwyq** [cycz/jdBuyMask#43]
python3 jdBuyMask_V2.py         
Traceback (most recent call last):
  File "/usr/lib/python3.7/configparser.py", line 788, in get
    value = d[option]
  File "/usr/lib/python3.7/collections/__init__.py", line 916, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.7/collections/__init__.py", line 908, in __missing__
    raise KeyError(key)
KeyError: 'messagetype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jdBuyMask_V2.py", line 28, in <module>
    messageType = global_config.getRaw('config', 'messageType')
  File "/root/jdBuyMask/config.py", line 20, in getRaw
    return self._configRaw.get(section, name)
  File "/usr/lib/python3.7/configparser.py", line 791, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'messagetype' in section: 'config'

**Comment by cycz** [comment]
> python3 jdBuyMask_V2.py
> Traceback (most recent call last):
> File "/usr/lib/python3.7/configparser.py", line 788, in get
> value = d[option]
> File "/usr/lib/python3.7/collections/**init**.py", line 916, in **getitem**
> return self.**missing**(key) # support subclasses that define **missing**
> File "/usr/lib/python3.7/collections/**init**.py", line 908, in **missing**
> raise KeyError(key)
> KeyError: 'messagetype'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "jdBuyMask_V2.py", line 28, in 
> messageType = global_config.getRaw('config', 'messageType')
> File "/root/jdBuyMask/config.py", line 20, in getRaw
> return self._configRaw.get(section, name)
> File "/usr/lib/python3.7/configparser.py", line 791, in get
> raise NoOptionError(option, section)
> configparser.NoOptionError: No option 'messagetype' in section: 'config'
你配置文件用新的试下，之前写错单词了。

**Comment by xinxijishuwyq** [comment]
> > python3 jdBuyMask_V2.py
> > Traceback (most recent call last):
> > File "/usr/lib/python3.7/configparser.py", line 788, in get
> > value = d[option]
> > File "/usr/lib/python3.7/collections/**init**.py", line 916, in **getitem**
> > return self.**missing**(key) # support subclasses that define **missing**
> > File "/usr/lib/python3.7/collections/**init**.py", line 908, in **missing**
> > raise KeyError(key)
> > KeyError: 'messagetype'
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "jdBuyMask_V2.py", line 28, in
> > messageType = global_config.getRaw('config', 'messageType')
> > File "/root/jdBuyMask/config.py", line 20, in getRaw
> > return self._configRaw.get(section, name)
> > File "/usr/lib/python3.7/configparser.py", line 791, in get
> > raise NoOptionError(option, section)
> > configparser.NoOptionError: No option 'messagetype' in section: 'config'
> > 你配置文件用新的试下，之前写错单词了。

好了，谢谢
