### ISSUE TITLE
cmd运行一段时间后停止

### ISSUE THREAD

**Issue by joe-jiao** [cycz/jdBuyMask#45]
你好，我在cmd上运行v2时，大概在查询200-1200之后便会停止。取消了快速编辑模式后也没有解决。怀疑是网络不稳定造成的停止，是否可以在网络不稳后过一段时间再尝试连接一次？

**Comment by cycz** [comment]
如果没有任何报错的话，应该不是程序内的原因，网络不稳定不会退出的

**Comment by joe-jiao** [comment]
谢谢

**Comment by QONE1918** [comment]
我这边运行20次到100次都会停止，cmd不再继续输出，感觉直接卡死了

**Comment by zhzhang747** [comment]
我这里运行几百次之后也会卡住，卡到第XXX次，然后没有任何输出，卡几十分钟甚至一两个小时也不动
