### ISSUE TITLE
可耻，shame on you 

### ISSUE THREAD

**Issue by Jiakui** [cycz/jdBuyMask#48]
程序员需要个屁的口罩。。。。

真正需要口罩的人，估计都是不懂爬虫的。。。

技术作恶！！！

**Comment by MIllionBenjamin** [comment]
不太懂 为什么程序员不需要口罩？

**Comment by cycz** [comment]
非常抱歉，
本意是给不懂爬虫得人使用的。
只是为了从黄牛的脚本中抢到一两份口罩

**Comment by longxiaX** [comment]
默认只能抢一个的，可以理解

**Comment by leeeeeeo** [comment]
瓜子啤酒鸡爪小板凳有售

**Comment by Lasciarti** [comment]
程序员也有家人，上github的也不都是程序员

**Comment by joe-jiao** [comment]
只是购买自己所需不是作恶

**Comment by mydomi** [comment]
Shame on you? 
How dare you! ROFL

**Comment by rofleed** [comment]
典型杠精

**Comment by QONE1918** [comment]
首先是人，其次才是程序员。懂爬虫的就不需要口罩了？你严密的逻辑去哪了？

**Comment by lxf880516** [comment]
我也不会python，步骤很详细跟着一步步学习的，程序员都写代码抢口罩吧。普通人不会，这个帖子正好扭转了，普通人和程序员的不平等。为了抢口罩，学习了一门语言，哈哈。

**Comment by woszz** [comment]
我也会英语
