### ISSUE TITLE
有货的商品判定为已下架商品

### ISSUE THREAD

**Issue by Newcomer365** [cycz/jdBuyMask#5]
有货的商品被判定为已下架商品

**Comment by cycz** [comment]
> 有货的商品被判定为已下架商品

商品链接给我试下

**Comment by Newcomer365** [comment]
> > 有货的商品被判定为已下架商品
> 
> 商品链接给我试下

https://item.m.jd.com/product/100008261832.html?utm_campaign=t_1001328990

**Comment by zjfjiayou** [comment]
我也遇到了
https://item.jd.com/63642372027.html

**Comment by cycz** [comment]
> 我也遇到了
> https://item.jd.com/63642372027.html

重新啦一下代码，刚刚弄的有问题
