### ISSUE TITLE
【V3.1】解决V3只能单商品,使用V2和V3的优点极速下单

### ISSUE THREAD

**Issue by cexll** [cycz/jdBuyMask#55]
https://github.com/cexll/jdBuyMask (V3.1版本)

**Comment by sxml** [comment]
> [https://github.com/cexll/jdBuyMask（V3.1](https://github.com/cexll/jdBuyMask)版本）

怎么添加多商品? configDemo 里 v3 还是只能一个啊

**Comment by cexll** [comment]
再次更新

**Comment by cexll** [comment]
exe打包,运行快速
