### ISSUE TITLE
eid与fp如何获取呢？

### ISSUE THREAD

**Issue by 20150561000** [cycz/jdBuyMask#6]
eid与fp如何获取呢？

**Comment by wwwlwr** [comment]
随便买个东西在提交订单的页面运行下
var eid = $('#eid').val();
var fp = $('#fp').val();
var trackId = getTakId();
var riskControl = $('#riskControl').val();
console.log(`eid = ${eid}\nfp = ${fp}\ntrack_id = ${trackId}\nrisk_control = ${riskControl}`);
