### ISSUE TITLE
有人使用这个当倒爷，建议暂时特殊时期先关闭

### ISSUE THREAD

**Issue by dream2333** [cycz/jdBuyMask#71]
身边就有一些人干二道贩子的活

**Comment by Denis-Oakley** [comment]
可以试着减少说明，增加配置的复杂度来提高门槛

**Comment by zeng-kun** [comment]
想问现在有人买到吗？应该没有人买到吧

**Comment by mentospcg** [comment]
我想起了那一句技术无罪……     人性太险恶。
ps. 我也还没有买到口罩

**Comment by ziwux** [comment]
赞同减少说明的那位用户，保留提示性说明即可，毕竟技术无罪，做技术交流即可。

**Comment by xesp** [comment]
我说怎么不好用了。这些人太可恶了。

**Comment by murphy-li** [comment]
某种程度上，文档不要写太详细，让懂技术的人能够配置成功就可以，然后提醒懂技术的不要滥用技术。
某种程度上现在技术滥用就是因为写的文档太详细了，谁都会用，但是不写详细又违背了让大家都用的初衷，可以稍微复杂些，配置这个需要些时间成本，然后别有用心的人就会被劝退。

**Comment by cycz** [comment]
没买到的可以进群，收集一下出货比较多的skuid

**Comment by mentospcg** [comment]
> 没买到的可以进群，收集一下出货比较多的skuid

可以提供一下群号吗？

**Comment by cntink** [comment]
说实话，我是自用，可是这个脚本一次也没给我买到过。。。。货号也填了20来个，一到下单就失败了，哎！

**Comment by murphy-li** [comment]
> 没买到的可以进群，收集一下出货比较多的skuid

老哥，群是哪个？

**Comment by hzdlive** [comment]
群员满了，没有办法进了

**Comment by lidapang** [comment]
我也没买到，验证码一直错误。

**Comment by xesp** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
