### ISSUE TITLE
自用求exe版本

### ISSUE THREAD

**Issue by jcyh6923** [cycz/jdBuyMask#78]
坐标浙江，过年到现在一直内抢到过口罩，今天google搜索到加qq群也加不进，希望发一份exe的，邮箱896997@gmail.com

**Comment by SteveYanzhi** [comment]
920311747@qq.com我也需要

**Comment by tiqiuren** [comment]
能否给一份exe版本的，抢了一周了都抢不到，693633452@qq.com

**Comment by SteveYanzhi** [comment]
20




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tiqiuren"<notifications@github.com&gt;; 
发送时间: 2020年2月21日(星期五) 下午4:09
收件人: "cycz/jdBuyMask"<jdBuyMask@noreply.github.com&gt;; 
抄送: "gvfd"<920311747@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [cycz/jdBuyMask] 自用求exe版本 (#78)




能否给一份exe版本的，抢了一周了都抢不到，693633452@qq.com
